# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='mailing_list',
        ),
    ]
