# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0002_auto_20160531_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing_list',
            name='comment',
            field=models.TextField(default=datetime.datetime(2016, 6, 16, 18, 28, 17, 896354, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing_list',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2016, 6, 16, 18, 28, 26, 70276, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing_list',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2016, 6, 16, 18, 28, 36, 138330, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing_list',
            name='email',
            field=models.EmailField(blank=True, max_length=120),
        ),
    ]
