# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0003_auto_20160616_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mailing_list',
            new_name='Contact',
        ),
    ]
