# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0004_auto_20160616_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
