# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0008_auto_20160616_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
