# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0011_auto_20160617_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published',
            new_name='draft',
        ),
    ]
