# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0012_auto_20160617_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateField(),
        ),
    ]
