# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0014_remove_blog_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
    ]
