# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0016_auto_20160623_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 6, 24, 0, 1, 28, 958886, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
