# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='directory',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2016, 5, 31, 17, 28, 14, 861529, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
