# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20160531_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
