# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20160531_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directories',
            new_name='Tenant',
        ),
    ]
