# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_auto_20160531_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='room',
            field=models.CharField(choices=[('A01', 'A01'), ('A02', 'A03'), ('A04', 'A05')], max_length=30),
        ),
    ]
