# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
    ]
