# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=studio.models.tenant_image_location),
        ),
    ]
