# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_auto_20160623_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=studio.models.blog_image_location, width_field='width_field'),
        ),
    ]
