# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_auto_20160630_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
