# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import studio.models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0018_mailing_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('A01', 'A01'), ('A02', 'A02'), ('A03', 'A03'), ('A04', 'A04'), ('A05', 'A05'), ('A06', 'A06'), ('A07', 'A07'), ('A08', 'A08'), ('A09', 'A09'), ('A10', 'A10'), ('A11', 'A11'), ('A12', 'A12'), ('A13', 'A13'), ('A14', 'A14'), ('A15', 'A15'), ('A16', 'A16'), ('A17', 'A17'), ('A18', 'A18'), ('A19', 'A19'), ('A20', 'A20'), ('A21', 'A21'), ('A22', 'A22'), ('A23', 'A23'), ('A24', 'A24'), ('A25', 'A25'), ('A26', 'A26'), ('A27', 'A27'), ('A28', 'A28'), ('A29', 'A29'), ('A30', 'A30'), ('A31', 'A31'), ('A32', 'A32'), ('A33', 'A33'), ('A34', 'A34'), ('A35', 'A35'), ('A36', 'A36'), ('A37', 'A37'), ('A38', 'A38'), ('B01', 'B01'), ('B02', 'B02'), ('B03', 'B03'), ('B04', 'B04'), ('B05', 'B05'), ('B06', 'B06'), ('B07', 'B07'), ('B08', 'B08'), ('B09', 'B09'), ('B10', 'B10'), ('B11', 'B11'), ('B12', 'B12'), ('B13', 'B13'), ('B14', 'B14'), ('B15', 'B15'), ('B16', 'B16'), ('B17', 'B17'), ('B18', 'B18'), ('B19', 'B19'), ('B20', 'B20'), ('B21', 'B21'), ('B22', 'B22'), ('B23', 'B23'), ('B24', 'B24'), ('B25', 'B25'), ('B26', 'B26'), ('B27', 'B27'), ('B28', 'B28'), ('B29', 'B29'), ('B30', 'B30'), ('B31', 'B31'), ('B32', 'B32'), ('B33', 'B33'), ('B34', 'B34'), ('B35', 'B35'), ('B36', 'B36'), ('B37', 'B37'), ('B38', 'B38'), ('C01', 'C01'), ('C02', 'C02'), ('C03', 'C03'), ('C04', 'C04'), ('C05', 'C05'), ('C06', 'C06'), ('C07', 'C07'), ('C08', 'C08'), ('C09', 'C09'), ('C10', 'C10'), ('C11', 'C11'), ('C12', 'C12'), ('C13', 'C13'), ('C14', 'C14'), ('C15', 'C15'), ('C16', 'C16'), ('C17', 'C17'), ('C18', 'C18'), ('C19', 'C19'), ('C20', 'C20'), ('C21', 'C21'), ('C22', 'C22'), ('C23', 'C23'), ('C24', 'C24'), ('C25', 'C25'), ('C26', 'C26'), ('C27', 'C27'), ('C28', 'C28'), ('C29', 'C29'), ('C30', 'C30'), ('C31', 'C31'), ('C32', 'C32'), ('C33', 'C33'), ('C34', 'C34'), ('C35', 'C35'), ('C36', 'C36'), ('C37', 'C37'), ('C38', 'C38'), ('D01', 'D01'), ('D02', 'D02'), ('D03', 'D03'), ('D04', 'D04'), ('D05', 'D05'), ('D06', 'D06'), ('D07', 'D07'), ('D08', 'D08'), ('D09', 'D09')], max_length=30, unique=True)),
                ('size', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('image', models.ImageField(upload_to=studio.models.room_image_location)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=studio.models.blog_image_location),
        ),
    ]
