# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0019_auto_20160702_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='content',
            field=models.TextField(default=datetime.datetime(2016, 7, 2, 20, 58, 12, 838270, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
