# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_room_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='video_link',
            new_name='youtube_link',
        ),
        migrations.AddField(
            model_name='tenant',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
