# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0021_auto_20160703_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='content',
            field=models.TextField(max_length=140),
        ),
    ]
