# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0022_auto_20160704_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='content',
            field=models.TextField(max_length=140),
        ),
    ]
