# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0023_auto_20160704_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='content',
            field=models.TextField(max_length=400),
        ),
    ]
