# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-05 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0025_coworking_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2016, 12, 5, 10, 6, 42, 792632, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
