# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-05 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0026_auto_20161205_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coworking_space',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2016, 12, 5, 10, 10, 10, 316363, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
