# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0028_blog_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='cropping',
        ),
    ]
