# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_space', '0004_remove_contact_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
