# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 23:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event_space', '0005_remove_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 6, 20, 23, 31, 47, 756178, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
