# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_space', '0006_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
