# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_space', '0007_auto_20160620_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(),
        ),
    ]
