# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import event_space.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_space', '0008_auto_20160620_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=event_space.models.blog_image_location, width_field='width_field'),
        ),
    ]
