# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_space', '0010_blog_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
