# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import event_space.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_space', '0011_mailing_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=event_space.models.blog_image_location),
        ),
    ]
