# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_space', '0012_auto_20160701_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing_list',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
