# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_space', '0013_mailing_list_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mailing_list',
            new_name='Mailing',
        ),
    ]
